
https://jsonplaceholder.typicode.com/users

### sudo kill -9 $(lsof -t -i:3001)

POST https://jsonplaceholder.typicode.com/posts
Content-type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}

### app apis
GET http://localhost:3001/api/userRoles/all
###
GET http://localhost:3001/api/users/all
###
GET http://localhost:3001/api/403