
https://jsonplaceholder.typicode.com/users

### sudo kill -9 $(lsof -t -i:3001)

POST https://jsonplaceholder.typicode.com/posts
Content-type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}

### app apis
GET http://localhost:3001/api/userRoles/all
### a role
GET http://localhost:3001/api/userRoles/5f29d6218de5ff4a48a33a42
### all users
GET http://localhost:3001/api/users/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InByb2ZpbGUiOnsiZW1haWwiOiJhZ25lc3lhcGlAZ21haWwuY29tIiwidXNlck5hbWUiOiJ5LmFnbmVzIn0sImdlbmRlciI6IkZFTUFMRSIsInJvbGVzIjpbIjVmMmE4M2I1NTdlZTc3MTJlY2E0OTQ5NSJdLCJpc0FjdGl2ZSI6dHJ1ZSwiX2lkIjoiNWYyYTg1MmQ2OTdiOGMzNjM4NmFjNWUwIiwiZmlyc3ROYW1lIjoiYWduZXMiLCJsYXN0TmFtZSI6InlhcGkiLCJjcmVhdGVkQXQiOiIyMDIwLTA4LTA1VDEwOjA4OjQ1LjQxOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTA4LTA1VDEwOjA4OjQ1LjQxOFoiLCJfX3YiOjB9LCJpYXQiOjE1OTY2MjI3NzYsImV4cCI6MTU5NzUyMjc3Nn0.j-EgJNTL1ra8Pw4YP6Qe_w0SqAcf93Meq3A62qrm6Fg

###
### get user 5f29d6218de5ff4a48a33a41
GET http://localhost:3001/api/users/5f29e476aec06135e012fe4c
### add new user
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "firstName": "agnes" ,"lastName": "yapi" ,"roles": 2 ,"email": "agnesyapi@gmail.com" ,"password": "agnes.yapi", "gender": 2
}
### update user role
PUT http://localhost:3001/api/users/updateRole/5f29e476aec06135e012fe4c
Content-Type: application/json

{
    "type": 1 , "roleId": "5f29d6218de5ff4a48a33a42"
}
### delet user
DELETE  http://localhost:3001/api/users/5f29ed6b5e7bb624ac5f6703 

###

### user changeState
PUT http://localhost:3001/api/users/changeState/5f29ef5e5580994844493cfc


### user change password
PUT http://localhost:3001/api/users/changePassword/5f29d81feda8e451c805d858
Content-Type: application/json

{
    "password": "john3doe"
}
###
### TEST Collection
GET http://localhost:3001/api/test/all
### a test
GET http://localhost:3001/api/test/5f28632a1991f14bb8b66fbc
###
### Category Collection
GET http://localhost:3001/api/category/all
### a test
GET http://localhost:3001/api/category/5f28632a1991f14bb8b66fbd
### a test
DELETE  http://localhost:3001/api/category/5f294e22a087fd48ec6cea23

### a test
POST http://localhost:3001/api/category
Content-Type: application/json

{
    "roleName": "T",
    "creatorId" : "5f28632a1991f14bb8b66fbc"
}
###
PUT http://localhost:3001/api/category/5f294e22a087fd48ec6cea23
Content-Type: application/json

{
    "roleName": "Arts"
}
###
### login and signup section
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "email": "agnesyapi@gmail.com" ,"password": "agnes.yapi"
}
###
POST http://localhost:3001/api/signup
Content-Type: application/json

{
    "firstName": "pearl" ,"lastName": "tag" ,"roles": 4 ,"email": "pearltagn@gmail.com" ,"password": "tomgabson", "gender": 0
}
###

5f2949a24f1bdf27083d1e5e
GET http://localhost:3001/api/403

{"status":true,"data":{"profile":{"email":"agnesyapi@gmail.com","userName":"y.agnes"},"gender":"FEMALE","roles":["5f2a83b557ee7712eca49495"],"isActive":true,"_id":"5f2a852d697b8c36386ac5e0","firstName":"agnes","lastName":"yapi","createdAt":"2020-08-05T10:08:45.418Z","updatedAt":"2020-08-05T10:08:45.418Z","__v":0,"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InByb2ZpbGUiOnsiZW1haWwiOiJhZ25lc3lhcGlAZ21haWwuY29tIiwidXNlck5hbWUiOiJ5LmFnbmVzIn0sImdlbmRlciI6IkZFTUFMRSIsInJvbGVzIjpbIjVmMmE4M2I1NTdlZTc3MTJlY2E0OTQ5NSJdLCJpc0FjdGl2ZSI6dHJ1ZSwiX2lkIjoiNWYyYTg1MmQ2OTdiOGMzNjM4NmFjNWUwIiwiZmlyc3ROYW1lIjoiYWduZXMiLCJsYXN0TmFtZSI6InlhcGkiLCJjcmVhdGVkQXQiOiIyMDIwLTA4LTA1VDEwOjA4OjQ1LjQxOFoiLCJ1cGRhdGVkQXQiOiIyMDIwLTA4LTA1VDEwOjA4OjQ1LjQxOFoiLCJfX3YiOjB9LCJpYXQiOjE1OTY2MjI3NzYsImV4cCI6MTU5NzUyMjc3Nn0.j-EgJNTL1ra8Pw4YP6Qe_w0SqAcf93Meq3A62qrm6Fg"},"message":"Login successful | Token generated!"}